use reusable checks

diff --git a/.github/workflows/go_checks.yml b/.github/workflows/go_checks.yml
--- a/.github/workflows/go_checks.yml
+++ b/.github/workflows/go_checks.yml
@@ -11,61 +11,20 @@ on:
       - main
 
 jobs:
-  unit-test:
-    name: unit-test
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version-file: go.mod
-
-      - name: Run Tests
-        run: make test
-
-  go-mod-tidy:
-    name: go-mod-tidy
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version-file: go.mod
-
-      - name: Run Tidy
-        run: |
-          find . -type f -name 'go.mod' | while read -r svc; do
-            cd $(dirname "${svc}");
-            echo "In $(pwd)";
-            go mod tidy;
-            cd -;
-          done
-          git diff --exit-code
-
-  staticcheck:
-    name: staticcheck
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version-file: go.mod
-
-      - name: Run Staticcheck
-        run: |
-          go install honnef.co/go/tools/cmd/staticcheck@latest
-          find . -type f -name 'go.mod' | while read -r svc; do
-            cd $(dirname "${svc}");
-            echo "In $(pwd)";
-            staticcheck ./...;
-            cd -;
-          done
+  go_checks:
+    name: Go checks
+    uses: ./.github/workflows/reusable_go_checks.yml
+    with:
+      configure_git_goprivate: false
+      unit_test_cmd: make test
+      unit_test_report_coverage_cmd: |
+        make coverage
+        COVERAGE=$(go tool cover -func coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
+        COVERAGE_PASS=$(echo $COVERAGE 80 | awk '{ print ($1 >= $2) ? "true" : "false" }')
+        if [ $COVERAGE_PASS = "false" ]; then
+          echo "test coverage failed - expected >= 80 / actual = $COVERAGE"
+          exit 1
+        fi
+      go_version_file: "go.mod"
+    secrets:
+      go_dependency_fetcher_token: ${{ secrets.GO_DEPENDENCY_FETCH_TOKEN }}
